# glyph_801 – FRACTAL_QUANTUM_CORE
# A quantum-like computation seed using self-repeating fractal harmonics.

import cmath

def glyph_801(depth=5):
    """
    Returns a list of complex values generated by a recursive phase map.
    depth: recursion depth (>=1)
    """
    def recurse(level):
        if level == 0:
            return 1
        return cmath.exp(1j * recurse(level - 1))
    return [recurse(i) for i in range(1, depth + 1)]
